Correct repack.py mypy err (#816)
To fix the mypy errors caused by code introduced in https://github.com/MetOffice/CDDS/pull/788

Error was:
```
cdds/cdds/convert/repack.py:209: error: Assignment to variable "exc" outside except: block  [misc]
cdds/cdds/convert/repack.py:211: error: Trying to read deleted variable "exc"  [misc]
cdds/cdds/convert/repack.py:212: error: Trying to read deleted variable "exc"  [misc]
```
Those errors no longer occur after changing `exc` to `exception`